import { Consultant, Contract, Settings, ActionType } from './types'

export const mockConsultants: Consultant[] = [
  {
    id: 'c1',
    name: 'Ana Silva',
    role: 'Consultora Senior',
    active: true,
    isAttendant: false,
    fixedRemuneration: 3500,
    participatesInAverages: true,
    averagesStartDate: '2025-01-01',
  },
  {
    id: 'c2',
    name: 'Carlos Santos',
    role: 'Consultor Pleno',
    active: true,
    isAttendant: false,
    fixedRemuneration: 2800,
    participatesInAverages: true,
    averagesStartDate: '2025-01-01',
  },
  {
    id: 'c3',
    name: 'Beatriz Lima',
    role: 'Consultora Junior',
    active: true,
    isAttendant: false,
    fixedRemuneration: 2200,
    participatesInAverages: false,
  },
  {
    id: 'c4',
    name: 'Diego Oliveira',
    role: 'Atendente Pré-processual',
    active: true,
    isAttendant: true,
    fixedRemuneration: 1800,
    participatesInAverages: false,
  },
  {
    id: 'c5',
    name: 'Elaine Costa',
    role: 'Atendente Pré-processual',
    active: true,
    isAttendant: true,
    fixedRemuneration: 1800,
    participatesInAverages: false,
  },
]

export const mockActionTypes: ActionType[] = [
  { id: 'a1', name: 'Direito do Trabalhador', active: true },
  { id: 'a2', name: 'Direito do Consumidor', active: true },
  { id: 'a3', name: 'Direito Civil', active: true },
  { id: 'a4', name: 'Direito Bancário', active: true },
  { id: 'a5', name: 'Direito Previdenciário', active: true },
]

export const mockSettings: Settings = {
  goals: {
    individualContracts: 50,
    individualValue: 135000,
    groupContracts: 200,
    groupValue: 540000,
    ticketMedio: 2700,
  },
  tiers: [
    { min: 10, max: 29, percentage: 2.5 },
    { min: 30, max: 36, percentage: 5.0 },
    { min: 37, max: 49, percentage: 6.0 },
    { min: 50, max: 999, percentage: 10.0 },
  ],
  bonuses: {
    highValueThreshold: 3000,
    highValuePercentage: 1.0,
    maxInstallments: 12,
    installmentsPercentage: 2.0,
  },
  quarterTiers: [
    { contracts: 105, award: 1250 },
    { contracts: 120, award: 1625 },
    { contracts: 150, award: 2500 },
  ],
  ipca: {
    year: 2025,
    value: 4.83,
    appliedPercentage: 70,
  },
}

const currentYear = new Date().getFullYear()
const currentMonth = new Date().getMonth() + 1
const pad = (n: number) => n.toString().padStart(2, '0')

export const mockContracts: Contract[] = [
  {
    id: '1',
    clientName: 'Empresa Alpha Ltda',
    cpf: '12.345.678/0001-90',
    phone: '(11) 98765-4321',
    email: 'contato@alpha.com.br',
    consultantId: 'c1',
    attendantId: 'c4',
    actionTypeId: 'a1',
    date: `${currentYear}-${pad(currentMonth)}-10`,
    value: 3500,
    paymentMethod: 'Cartão',
    installments: 6,
    status: 'Ativo',
    downPaymentValue: 500,
    downPaymentMethod: 'PIX',
    downPaymentStatus: 'Sim',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    clientName: 'João Ferreira',
    cpf: '123.456.789-00',
    phone: '(11) 91234-5678',
    email: 'joao.ferreira@email.com',
    consultantId: 'c2',
    attendantId: 'c5',
    actionTypeId: 'a2',
    date: `${currentYear}-${pad(currentMonth)}-12`,
    value: 2800,
    paymentMethod: 'Boleto',
    installments: 12,
    status: 'Ativo',
    downPaymentValue: 280,
    downPaymentMethod: 'Boleto',
    downPaymentStatus: 'Sim',
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    clientName: 'Construtora Beta',
    cpf: '98.765.432/0001-10',
    phone: '(21) 99876-5432',
    email: 'financeiro@beta.com.br',
    consultantId: 'c3',
    attendantId: 'c4',
    actionTypeId: 'a3',
    date: `${currentYear}-${pad(currentMonth)}-15`,
    value: 5000,
    paymentMethod: 'PIX',
    installments: 1,
    status: 'Distrato Pendente',
    downPaymentValue: 1000,
    downPaymentMethod: 'Transferência',
    downPaymentStatus: 'Sim',
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    clientName: 'Comércio Silva',
    cpf: '456.789.123-45',
    phone: '(11) 95555-1234',
    email: 'silva@comercio.com',
    consultantId: 'c1',
    attendantId: 'c5',
    actionTypeId: 'a4',
    date: `${currentYear}-${pad(currentMonth)}-05`,
    value: 1500,
    paymentMethod: 'Cartão',
    installments: 10,
    status: 'Cancelado',
    cancellationDate: `${currentYear}-${pad(currentMonth)}-20`,
    cancellationReason: 'Desistência',
    internalFailure: false,
    downPaymentValue: 0,
    downPaymentMethod: 'Cartão',
    downPaymentStatus: 'Não',
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    clientName: 'Indústria Gama',
    cpf: '789.123.456-78',
    phone: '(31) 97777-8888',
    email: 'contato@gama.ind.br',
    consultantId: 'c2',
    attendantId: 'c4',
    actionTypeId: 'a5',
    date: `${currentYear}-${pad(currentMonth)}-02`,
    value: 4200,
    paymentMethod: 'Transferência',
    installments: 4,
    status: 'Revertido',
    downPaymentValue: 840,
    downPaymentMethod: 'Transferência',
    downPaymentStatus: 'Sim',
    createdAt: new Date().toISOString(),
  },
]
